apiVersion: v1
kind: Namespace
metadata:
  name: tensorflow-languagemodeling-electra
  labels:
    name: tensorflow-languagemodeling-electra
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-languagemodeling-electra
  namespace: tensorflow-languagemodeling-electra
  labels:
    app: tensorflow-languagemodeling-electra
spec:
  selector:
    matchLabels:
      app: tensorflow-languagemodeling-electra
  template:
    metadata:
      labels:
        app: tensorflow-languagemodeling-electra
    spec:
      containers:
        - name: tensorflow-languagemodeling-electra
          image: tensorflow-languagemodeling-electra
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          resources:
            limits:
              nvidia.com/gpu: 1
          args:
            - jupyter
            - lab
            - --ip=0.0.0.0
            - --no-browser
            - --allow-root
            - --port=8888
            - --NotebookApp.token=''
            - --NotebookApp.password=''
            - --NotebookApp.allow_origin='*'
            - --NotebookApp.base_url=/
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      volumes:
        - name: dshm
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.service.nodeport.port: "30888"
    kompose.service.type: nodeport
  creationTimestamp: null
  labels:
    app: tensorflow-languagemodeling-electra
  name: tensorflow-languagemodeling-electra
  namespace: tensorflow-languagemodeling-electra
spec:
  ports:
    - name: jupyterlab
      nodePort: 30888
      port: 8888
      targetPort: 8888
  selector:
    app: tensorflow-languagemodeling-electra
  type: NodePort
status:
  loadBalancer: {}
