---
- name: ensure rsyslog is installed
  package:
    name: rsyslog
    state: present

- name: configure syslog listener
  template:
    src: "01-deepops-listen.conf"
    dest: "/etc/rsyslog.d/01-deepops-listen.conf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: create directory for clients logs
  file:
    path: "{{ rsyslog_log_file_path }}"
    state: directory
    owner: "syslog"
    group: "syslog"
    mode: "0755"
  notify:
  - reload rsyslog
