---
- name: Check for Ubuntu version
  fail:
    msg: "Role supports Ubuntu 20.04 only"
  when: ansible_distribution_version != "20.04"

- name: include os specific variables
  include_vars: ubuntu-20.04.yml

- name: install dmidecode
  apt:
    name: dmidecode
    state: present
    update_cache: yes

# Housekeeping
- name: register DGX product name
  command: "dmidecode --string system-product-name"
  register: dgx_name

- name: register DGX-1 serial number
  command: "dmidecode --string system-serial-number"
  register: dgx1_serial
  when: ansible_product_name is search("DGX-1")

- name: register DGX-2 serial number
  command: "dmidecode --string chassis-serial-number"
  register: dgx2_serial
  when: ansible_product_name is search("DGX-2")

- name: register DGXA100 serial number
  command: "dmidecode --string chassis-serial-number"
  register: dgxa100_serial
  when: ansible_product_name is search("DGXA100")

- name: figure out which serial number we ended up with
  set_fact:
    dgx_serial: "{{ dgx1_serial.stdout }}"
  when: dgx1_serial.skipped is not defined

- name: figure out which serial number we ended up with
  set_fact:
    dgx_serial: "{{ dgx2_serial.stdout }}"
  when: dgx2_serial.skipped is not defined

- name: figure out which serial number we ended up with
  set_fact:
    dgx_serial: "{{ dgxa100_serial.stdout }}"
  when: dgxa100_serial.skipped is not defined

- name: fail if we don't recognize the DGX system
  fail:
    msg: "Unknown DGX model: {{ ansible_product_name }}"
  when: dgx_serial is undefined

- name: update dgx platform file
  blockinfile:
    path: /etc/dgx-release
    create: yes
    block: |
      DGX_NAME="DGX Server"
      DGX_PRETTY_NAME="NVIDIA DGX Server"
      DGX_PLATFORM="DGX Server for {{ dgx_name.stdout }}"
      DGX_SERIAL_NUMBER="{{ dgx_serial }}"

# Repos and installs
- name: remove ubuntu nvidia driver ppa if installed
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: absent

- name: add DGX repo key
  ansible.builtin.apt_key:
    url: "{{ nvidia_dgx_os5_ubuntu_gpgkey }}"
    state: present

- name: add DGX repo
  template:
    src: dgxos5.list.j2
    dest: /etc/apt/sources.list.d/dgx-temp.list
    mode: 0644

- name: update apt cache
  apt:
    update_cache: yes

- name: install prerequisites
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ G_PREREQS }}"
    - "{{ G_SETUP_PKGS }}"

- name: install DGX repo package
  apt:
    name: "{{ item }}"
    update_cache: yes
    dpkg_options: "force-confdef,force-confold"
  with_items:
    - "{{ G_DGX_REPO_PKG }}"

- name: remove temporary repo package
  file:
    path: /etc/apt/sources.list.d/dgx-temp.list
    state: absent

- name: install more packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    dpkg_options: "force-confdef,force-confold"
  with_items:
    - "{{ G_PKGS_DEFAULT }}"

- name: install DGX-1 packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ G_DGX_COMMON_PKGS }}"
    - "{{ G_DGX1_PKGS }}"
  when: ansible_product_name is search("DGX-1")
  notify:
    - restart docker

- name: install DGX-2 packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ G_DGX_COMMON_PKGS }}"
    - "{{ G_DGX2_PKGS }}"
  when: ansible_product_name is search("DGX-2")
  notify:
    - restart docker

- name: install DGXA100 packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ G_DGX_COMMON_PKGS }}"
    - "{{ G_DGX_A100_PKGS }}"
  when: ansible_product_name is search("DGXA100")
  notify:
    - restart docker

# Post-install stuff
- name: disable release update prompt
  lineinfile:
    path: /etc/update-manager/release-upgrades
    regexp: '^Prompt=.*'
    line: Prompt=never

- name: add ipmi kernel module at boot
  lineinfile:
    path: /etc/modules
    line: ipmi_devintf

- name: enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - openibd
    - dcgm
    - nvidia-dcgm
    - nvidia-persistenced
    - nvidia-fabricmanager

- name: enable PXE/UEFI on MLNX interfaces
  command: /usr/sbin/mlnx_pxe_setup.bash

- name: configure nv peer mem service startup
  command: /usr/sbin/update-rc.d nv_peer_mem defaults

- name: enable nvidia fabricmanager
  systemd:
    name: nvidia-fabricmanager
    state: started
    enabled: yes
  when: ansible_product_name is search("DGXA100")

- name: disable srp services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  when: ansible_product_name is search("DGXA100")
  with_items:
    - srp_daemon
    - srptools

# setup_data_drive "/dev/sdb1" "dgx1cache"
- name: create raid directory for raid cache mount point
  file:
    path: "{{ cachefilesd_cache_dir }}"
    state: directory
    mode: "{{ cachefilesd_cache_dir_mode }}"

- name: configure cachefilesd
  template:
    src: cachefilesd.conf.j2
    dest: /etc/cachefilesd.conf

# Misc stuff
- name: enable and start {{ item }} service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - nvidia-persistenced
    - dcgm

- name: restart docker service just in case...
  systemd:
    name: docker
    state: restarted
    enabled: yes
