---
# Ensure OpenShift packages are installed
- include: ../bootstrap/bootstrap-openshift.yml

# GPU operator
- hosts: localhost
  become: yes
  tasks:
    - name: Install helm chart for GPU operator
      include_role:
        name: nvidia-gpu-operator
      run_once: true
  tags:
    - nvidia
    - nvidia-gpu-operator
