---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: cachefilesd-ubuntu-1804
    image: geerlingguy/docker-ubuntu1804-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    tmpfs:
    - /run
    - /tmp
    pre_build_image: true
  - name: cachefilesd-ubuntu-2004
    image: geerlingguy/docker-ubuntu2004-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    tmpfs:
    - /run
    - /tmp
    pre_build_image: true
  - name: cachefilesd-centos-7
    image: geerlingguy/docker-centos7-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    tmpfs:
    - /run
    - /tmp
    pre_build_image: true
  - name: cachefilesd-centos-8
    image: geerlingguy/docker-centos8-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    tmpfs:
    - /run
    - /tmp
    pre_build_image: true
provisioner:
  name: ansible
  ansible_args:
  - -vv
  inventory:
    group_vars:
      all:
        nis_domain: "example.com"
        nis_server: "nis.example.com"
verifier:
  name: ansible
