---

- name: Configure login on compute.
  hosts: slurm-master
  become: yes
  tasks:
    - name: Run a script to enable slurm login on compute node.
      script:
        cmd: ../../scripts/generic/patch_compute_node_for_login.sh
      args:
        creates: /etc/slurm/login_enable
  tags:
    - config
